import type { NextPage } from "next"
import Head from "next/head"
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const Home: NextPage = () => {
  return (
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* <!-- Open Graph / Facebook --> */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://somelink" />
        <meta property="og:title" content="test-repo" />
        <meta
          property="og:description"
          content=""
        />
        <meta
          property="og:image"
          content=""
        />
        {/* <!-- Twitter --> */}
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://somelink" />
        <meta property="twitter:title" content="test-repo" />
        <meta
          property="twitter:description"
          content=""
        />
        <meta
          property="twitter:image"
          content="https://somelink"
        />
      </Head>

  )
}

export const getStaticProps = async ({ locale }: { locale: string }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"])),
  },
});

export default Home;
